#!/usr/bin/env python3
"""Generate sec/numbers.tex from the locked SafeWorld result records.

Every number that appears in the paper body is emitted here as a LaTeX macro,
read directly from the hash-registered JSON artifacts. Nothing is hand-copied.

Usage:
    python3 make_numbers.py                 # pre-FN1: FN1 macros -> \fnpending
    python3 make_numbers.py --fn1 PATH      # post-FN1: fill N1..N4 from the
                                            # FN1 analysis JSON (same schema
                                            # as the FM1 analysis file)

Re-run after FN1 finalizes (~2026-08-10), then flip the \iffnonedone /
\iffnonepass switches in main.tex.
"""
import argparse
import json
import sys
from pathlib import Path

ART = Path("/home/qiren/alpasafe/safeworld-alpamayo/artifacts")
FM1 = ART / "safeworld_t26g_fm1_full_l2_matched_selector_experiment/20260803T132326Z"
FN0 = ART / "safeworld_t26g_fn0_l3_pathway_consolidation_preregistration/20260803T210139Z"
E0 = ART / "safeworld_t26g_e0_top_of_list_selector_resolution/20260727T042825Z"

SOURCES = {
    "fm1_analysis": FM1 / "results/t26g_fm1_analysis.json",
    "fm1_gpu_gate": FM1 / "results/t26g_fm1_gpu_gate.json",
    "fn0_power": FN0 / "contracts/t26g_fn0_power_and_sample_size_contract.json",
    "fn0_conformance": FN0 / "results/t26g_fn0_conformance_and_budget.json",
    "e0_selector": E0 / "contracts/t26g_e0_selector_loss_contract.json",
}

OUT = Path(__file__).parent / "sec" / "numbers.tex"

# LaTeX macro names cannot contain digits.
WORD = {"M1": "MOne", "M2": "MTwo", "M3": "MThree", "M4": "MFour", "M5": "MFive",
        "N1": "NOne", "N2": "NTwo", "N3": "NThree", "N4": "NFour"}
EP = {
    "K8_regret": ("KEightRegret", 4),
    "K8_top1": ("KEightTopOne", 3),
    "K5_regret": ("KFiveRegret", 4),
    "K5_top1": ("KFiveTopOne", 3),
    "K2_regret": ("KTwoRegret", 4),
    "K2_top1": ("KTwoTopOne", 3),
    "K8_pairwise": ("KEightPairwise", 3),
    "K8_best_vs_rest": ("KEightBestVsRest", 3),
}

lines = []


def emit(name, body):
    lines.append(f"\\newcommand{{\\{name}}}{{{body}}}")


def f_signed(x, d):
    return f"{x:+.{d}f}"


def f_abs(x, d):
    return f"{x:.{d}f}"


def ci_macro(prefix, stat, d):
    m, lo, hi = stat["mean"], stat["ci95_low"], stat["ci95_high"]
    emit(prefix + "Mean", f"\\ensuremath{{{f_signed(m, d)}}}")
    emit(prefix + "Lo", f"\\ensuremath{{{f_signed(lo, d)}}}")
    emit(prefix + "Hi", f"\\ensuremath{{{f_signed(hi, d)}}}")
    emit(prefix + "CI",
         f"\\ensuremath{{{f_signed(m, d)}\\;[{f_signed(lo, d)},\\,{f_signed(hi, d)}]}}")
    emit(prefix + "Bracket",
         f"\\ensuremath{{[{f_signed(lo, d)},\\,{f_signed(hi, d)}]}}")


def comparison_block(comps, mapping):
    for raw, word in mapping.items():
        if raw not in comps:
            continue
        c = comps[raw]
        for ep_raw, (ep_word, d) in EP.items():
            if ep_raw in c and isinstance(c[ep_raw], dict):
                ci_macro(word + ep_word, c[ep_raw], d)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fn1", type=Path, default=None,
                    help="FN1 analysis JSON (fills N1..N4); omit before FN1")
    args = ap.parse_args()

    data = {}
    for key, path in SOURCES.items():
        with open(path) as fh:
            data[key] = json.load(fh)

    lines.append("% AUTO-GENERATED by make_numbers.py -- DO NOT EDIT BY HAND.")
    lines.append("% Sources (hash-registered records):")
    for key, path in SOURCES.items():
        lines.append(f"%   {key}: {path}")
    lines.append("% Regenerate: python3 make_numbers.py [--fn1 <fn1_analysis.json>]")
    lines.append("")

    # ---------------- cohort / design constants ----------------
    an = data["fm1_analysis"]
    emit("nScenes", str(an["n_scenes"]))
    emit("nGroups", str(an["n_groups"]))
    emit("nScoresTotal", f"{an['n_groups'] * 8:,}".replace(",", "{,}"))
    emit("TieEps", "\\ensuremath{10^{-6}}")

    # ---------------- FM1 paired comparisons M1..M5 ----------------
    comparison_block(an["comparisons"], {k: v for k, v in WORD.items() if k.startswith("M")})

    # ---------------- FM1 ablations (FULL arm, inference-time) ----------------
    abl = an["ablations"]
    abl_map = {"WRONG_SCENE_FULL_L2": "AblWrongScene",
               "ZERO_FULL_L2": "AblZeroScene",
               "LAST_TOKEN_ONLY_DIAGNOSTIC": "AblLastTokenDiag"}
    for raw, word in abl_map.items():
        ci_macro(word + "Regret", abl[raw]["delta_K8_regret_vs_NORMAL"], 4)
        ci_macro(word + "TopOne", abl[raw]["delta_K8_top1_vs_NORMAL"], 3)

    # ---------------- FM1 absolute levels (battery, NORMAL) ----------------
    bat = an["battery"]
    arm_map = {"P_LASTTOKEN_L3_MATCHED_CONS": "Lasttoken",
               "P_NULL_SCENE_MATCHED_CONS": "Null",
               "P_FULL_L2_CONS": "Full",
               "P_A_LEGACY_MATCHED": "Legacy"}
    for raw, word in arm_map.items():
        n = bat[raw]["NORMAL"]
        emit(f"Abs{word}KEightRegret", f"\\ensuremath{{{f_abs(n['K8_regret'], 4)}}}")
        emit(f"Abs{word}KEightTopOne", f"\\ensuremath{{{f_abs(n['K8_top1'], 3)}}}")
        emit(f"Abs{word}KEightPairwise", f"\\ensuremath{{{f_abs(n['K8_pairwise'], 3)}}}")
        emit(f"Abs{word}CollisionAuroc", f"\\ensuremath{{{f_abs(n['collision_auroc'], 3)}}}")
        emit(f"Abs{word}Ade", f"\\ensuremath{{{f_abs(n['ade'], 3)}}}")
    # FULL-arm inference-time ablation absolute top-1 levels (for Fig.4 text)
    fullb = bat["P_FULL_L2_CONS"]
    emit("AbsFullDiagKEightTopOne",
         f"\\ensuremath{{{f_abs(fullb['LAST_TOKEN_ONLY_DIAGNOSTIC']['K8_top1'], 3)}}}")
    emit("AbsFullWrongKEightTopOne",
         f"\\ensuremath{{{f_abs(fullb['WRONG_SCENE_FULL_L2']['K8_top1'], 3)}}}")
    emit("AbsFullZeroKEightTopOne",
         f"\\ensuremath{{{f_abs(fullb['ZERO_FULL_L2']['K8_top1'], 3)}}}")

    # ---------------- FM1 auxiliary-head deltas (FULL - LASTTOKEN) ----------------
    aux = an["aux_deltas_full_minus_lasttoken"]
    for raw, word, d in [("ade", "AuxAde", 3), ("fde", "AuxFde", 3),
                         ("collision_auroc", "AuxCollision", 3),
                         ("progress_mae", "AuxProgress", 3)]:
        ci_macro(word, aux[raw], d)
    emit("AuxCollisionNScenes", str(aux["collision_auroc"]["n_scenes"]))

    # ---------------- FN0 power & sample size ----------------
    pw = data["fn0_power"]
    emit("FnNTotal", str(pw["n_total_required"]))
    emit("FnNExisting", str(pw["n_primary_existing"]))
    emit("FnNNewPreAttrition", str(pw["n_new_before_attrition"]))
    emit("FnNNew", str(pw["n_new_final_acquisition_target"]))
    emit("FnAcquisitionTotal",
         str(pw["n_primary_existing"] + pw["n_new_final_acquisition_target"]))
    emit("FnMde", f"\\ensuremath{{{f_abs(pw['mde_fn_regret'], 5)}}}")
    emit("FnSdPaired", f"\\ensuremath{{{f_abs(pw['sd_paired_regret_M5'], 4)}}}")
    emit("FnPowerAchieved",
         f"\\ensuremath{{{f_abs(pw['achieved_power']['at_n_total_required'], 3)}}}")
    emit("FnPowerAtPool",
         f"\\ensuremath{{{f_abs(pw['achieved_power']['at_pool_exhaustion_all_survive'], 3)}}}")
    emit("FnTopOneMde",
         f"\\ensuremath{{{f_abs(pw['top1_mde']['at_n_total_required'], 3)}}}")
    emit("FnPoolRemaining", str(pw["eligible_pool"]["remaining_true"]))

    # ---------------- efficiency: deployment (last-token) vs full reader ----------------
    conf = data["fn0_conformance"]
    meas = conf["measurements"]
    emit("EffParams", f"{meas['trainable_parameters']['F_LASTTOKEN_L3_MATCHED_CONS']:,}"
         .replace(",", "{,}"))
    emit("EffLtMedianMs", f"\\ensuremath{{{meas['median_K8_forward_latency_ms']:.2f}}}")
    emit("EffLtTailMs", f"\\ensuremath{{{meas['p95_K8_forward_latency_ms']:.2f}}}")
    emit("EffLtMemMb", f"\\ensuremath{{{meas['peak_incremental_inference_bytes'] / 1e6:.1f}}}")
    gpu = data["fm1_gpu_gate"]["measurements"]
    emit("EffFullMedianMs", f"\\ensuremath{{{gpu['median_K8_forward_latency_ms']:.2f}}}")
    emit("EffFullTailMs", f"\\ensuremath{{{gpu['p95_K8_forward_latency_ms']:.2f}}}")
    emit("EffFullMemMb", f"\\ensuremath{{{gpu['peak_incremental_inference_bytes'] / 1e6:.1f}}}")
    emit("EffTrainPeakMb",
         f"\\ensuremath{{{gpu['fwd_bwd_peak_incremental_vram_bytes_per_worker'] / 1e6:.1f}}}")
    emit("EffMemRatio",
         f"\\ensuremath{{{gpu['peak_incremental_inference_bytes'] / meas['peak_incremental_inference_bytes']:.0f}}}")
    ceil = conf["ceilings"]
    emit("EffCeilMedianMs", f"\\ensuremath{{{ceil['median_incremental_K8_latency_ms_max']:.0f}}}")
    emit("EffCeilTailMs", f"\\ensuremath{{{ceil['p95_incremental_K8_latency_ms_max']:.0f}}}")
    emit("EffCeilMemGb",
         f"\\ensuremath{{{ceil['peak_incremental_inference_memory_bytes_max'] / 2**30:.0f}}}")
    emit("EffCeilParams", f"{ceil['trainable_parameters_max']:,}".replace(",", "{,}"))

    # ---------------- E0 selector-loss constants ----------------
    e0 = data["e0_selector"]
    emit("SelTau", f"\\ensuremath{{{e0['tau']}}}")
    emit("SelCoef", f"\\ensuremath{{{e0['selector_loss_coefficient']}}}")
    det = data["fn0_conformance"]["detail"]["e0_pathology_detected_and_logged"]
    emit("SelGradSat", f"\\ensuremath{{{det['frozen_selector_grad_norm']:.1f}}}")
    v = det["rejected_softmax_grad_norm"]
    import math
    exp10 = math.floor(math.log10(v))
    emit("SelGradVanish",
         f"\\ensuremath{{{v / 10**exp10:.1f}\\times 10^{{{exp10}}}}}")

    # ---------------- FN1 comparisons (pending until --fn1) ----------------
    lines.append("")
    lines.append("% ---- FN1 (T26G-FN1) endpoints: PENDING until the FN1 analysis JSON exists ----")
    n_words = {k: v for k, v in WORD.items() if k.startswith("N")}
    if args.fn1 is not None:
        fn1 = json.load(open(args.fn1))
        c = fn1["comparisons"]
        # FN1 analyzer emits dual-candidate keys (no nominated arm):
        # headline N-slots follow the CKPT candidate (the FM1-continuity
        # arm the power analysis was sized for); SEL gets parallel macros.
        alias = {"N1": "N1_CKPT", "N2": "N2_CKPT", "N3": "N3", "N4": "N4"}
        comparison_block(
            {k: c[v] for k, v in alias.items() if v in c}, n_words)
        comparison_block({"N1_SEL": c["N1_SEL"]}, {"N1_SEL": "NOneSel"})
        comparison_block({"N2_SEL": c["N2_SEL"]}, {"N2_SEL": "NTwoSel"})
        emit("FnOneNScenes", str(fn1["n_scenes"]))
    else:
        for word in n_words.values():
            for ep_word, _ in EP.values():
                for suffix in ("Mean", "Lo", "Hi", "CI", "Bracket"):
                    emit(word + ep_word + suffix, "\\fnpending")
        emit("FnOneNScenes", "\\fnpending")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    n_macros = sum(1 for l in lines if l.startswith("\\newcommand"))
    print(f"wrote {OUT} ({n_macros} macros)")


if __name__ == "__main__":
    sys.exit(main())
